service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: arn:aws:s3:::task-5-bucket/uploaded/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:eu-north-1:861385611523:catalogItemsQueue

# you can overwrite defaults here
  stage: dev
  region: eu-north-1

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: task-5-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true